### ISSUE TITLE
Error: Cannot find module 'bplist-parser'

### ISSUE THREAD

**Issue by hansaliyad1** [RocketChat/Rocket.Chat.Cordova#44]
Cordova prepare throws an error. Don't know what is wrong. Any help would me appreciated. Thanks

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'bplist-parser'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:20:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by rodrigok** [comment]
@hansaliyad1 try to execute a `npm install` before the `cordova prepare`

**Comment by gregmartyn** [comment]
I had to:
npm install bplist-parser minimatch inherits path-is-absolute inflight once
to get it to work

**Comment by piyush-avantsoft** [comment]
its not proper solution though i am getting error.

**Comment by 3jFernando** [comment]
Tengo el mismo error, no pude continuar, estoy trabando en ubuntu 14.04.3 por favor si alguien logra solucionarlo que avise gracias...

**Comment by geekgonecrazy** [comment]
> Tengo el mismo error, no pude continuar, estoy trabando en ubuntu 14.04.3 por favor si alguien logra solucionarlo que avise gracias...

Translation: 

> I have the same error, you can not go on, I'm working on ubuntu 14.04.3 please alert me if someone manages to fix it thanks ...

**Comment by rodrigok** [comment]
Ok, I started a ubuntu VM and I got the same error using the npm installed from apt-get.

I did update the npm `npm install npm -g` to version `3.5.3`
I removed the cordova installation `npm uninstall cordova -g`
And installed again `npm install cordova -g`

That worked for me, can you guys try it?

**Comment by 3jFernando** [comment]
Eres grande amigo, muchas gracias rodrigok :+1:  :100:

**Comment by AsadAlihp** [comment]
I have the same error , I just updated npm and then it worked :)

**Comment by kirotawa** [comment]
I update my node, my npm, remove cordova , reinstall latest , install all this:
sudo npm install -g bplist-parser
sudo npm install -g minimatch
sudo npm install -g inherits
sudo npm install -g path-is-absolute
sudo npm install -g inflight
sudo npm install -g once

So, I just type a workaround here because my s link was point to some mess installation, and just change it to 'the right' installation, it's ugly as hell but now it's workring
